# Generated by Django 6.1.1 on 2026-10-04 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_alter_doctor_options_alter_specialty_options_and_more'),
        ('patients', '0002_alter_patient_options_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان درمان')),
                ('diagnosis', models.TextField(blank=True, verbose_name='تشخیص')),
                ('tooth_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='شماره دندان')),
                ('status', models.CharField(choices=[('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('incomplete', 'نیاز به بررسی'), ('cancelled', 'لغو شده')], default='in_progress', max_length=20, verbose_name='وضعیت')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='doctors.doctor', verbose_name='پزشک')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'درمان',
                'verbose_name_plural': 'درمان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
