# Generated by Django 6.1.1 on 2026-09-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'بیمار'), ('DOCTOR', 'پزشک'), ('ADMIN', 'مدیر')], default='PATIENT', max_length=20),
        ),
    ]
