# Generated by Django 6.1.1 on 2026-10-04 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_medicalcondition_medicalrecord'),
        ('doctors', '0002_alter_doctor_options_alter_specialty_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'time'], 'verbose_name': 'نوبت', 'verbose_name_plural': 'نوبت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'verbose_name': 'برنامه کاری پزشک', 'verbose_name_plural': 'برنامه\u200cهای کاری پزشکان'},
        ),
        migrations.AlterModelOptions(
            name='medicalcondition',
            options={'verbose_name': 'بیماری', 'verbose_name_plural': 'بیماری\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'verbose_name': 'سابقه پزشکی', 'verbose_name_plural': 'سوابق پزشکی'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='تاریخ نوبت'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor', verbose_name='پزشک'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='بیمار'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار'), ('CONFIRMED', 'تایید شده'), ('CANCELLED', 'لغو شده'), ('COMPLETED', 'انجام شده')], default='PENDING', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(verbose_name='ساعت نوبت'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(5, 'شنبه'), (6, 'یکشنبه'), (0, 'دوشنبه'), (1, 'سه\u200cشنبه'), (2, 'چهارشنبه'), (3, 'پنجشنبه'), (4, 'جمعه')], verbose_name='روز هفته'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor', verbose_name='پزشک'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='end_time',
            field=models.TimeField(verbose_name='ساعت پایان'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='start_time',
            field=models.TimeField(verbose_name='ساعت شروع'),
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='diagnosed_at',
            field=models.DateField(verbose_name='تاریخ تشخیص'),
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosed_conditions', to='doctors.doctor', verbose_name='پزشک تشخیص\u200cدهنده'),
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='بیماری فعال'),
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام بیماری'),
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='notes',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_conditions', to=settings.AUTH_USER_MODEL, verbose_name='بیمار'),
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_conditions', to='doctors.specialty', verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(blank=True, verbose_name='تشخیص'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='doctors.doctor', verbose_name='پزشک'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت پزشک'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL, verbose_name='بیمار'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='doctors.specialty', verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment',
            field=models.TextField(blank=True, verbose_name='درمان'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='visit_date',
            field=models.DateField(verbose_name='تاریخ مراجعه'),
        ),
    ]
