# Generated by Django 6.1.1 on 2026-10-04 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'پزشک', 'verbose_name_plural': 'پزشکان'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'تخصص', 'verbose_name_plural': 'تخصص\u200cها'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='area',
            field=models.CharField(blank=True, max_length=100, verbose_name='منطقه'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, verbose_name='درباره پزشک'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(default=0, verbose_name='سابقه کاری'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='تصویر پزشک'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='doctors.specialty', verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام تخصص'),
        ),
    ]
